#端口配置
server:
  port: 8080

#配置分库分表
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: userId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.148.55:3306/smart_lottery?useUnicode=true
        username: root
        password: root
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.148.55:3306/smart_lottery_01?useUnicode=true
        username: root
        password: root
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.148.55:3306/smart_lottery_02?useUnicode=true
        username: root
        password: root

# Dubbo 广播方式配置
dubbo:
  application:
    name: smart-lottery
    version: 1.0.0
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.easyjava.lottery.rpc

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    cn.easyjava.lottery: debug
