#端口配置
server:
  port: 8080
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://123.56.148.55:3306/smart_lottery?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
# Dubbo 广播方式配置
dubbo:
  application:
    name: smart-lottery
    version: 1.0.0
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.easyjava.lottery.rpc

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/*.xml
